name: vhack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  appinio_swiper: ^2.1.0
  flutter_card_swiper: ^7.0.0
  styled_widget: ^0.4.1
  go_router: ^13.2.1
  curved_labeled_navigation_bar: ^2.0.2
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpeg
    - assets/profile1.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: .\fonts\Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: .\fonts/SourceSansPro-Regular.ttf
    - family: Madimi
      fonts:
        - asset: .\fonts\MadimiOne-Regular.ttf
    - family: Varela
      fonts: 
        - asset: .\fonts\VarelaRound-Regular.ttf
    - family: RoundBlack
      fonts: 
        - asset: .\fonts\MPLUSRounded1c-Black.ttf
    - family: RoundBold
      fonts:
        - asset: .\fonts\MPLUSRounded1c-ExtraBold.ttf